// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqmFGuquOjRmBnuw_6BttjbP2jfHD59Ik',
    appId: '1:936033037093:web:41f752fb7f4b01fed488cc',
    messagingSenderId: '936033037093',
    projectId: 'niche-ai-mvp-0215',
    authDomain: 'niche-ai-mvp-0215.firebaseapp.com',
    storageBucket: 'niche-ai-mvp-0215.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfvoR4Vauvjxx1cCxmvTyjiiLRlPDL9Fc',
    appId: '1:936033037093:android:85339ea64dab7166d488cc',
    messagingSenderId: '936033037093',
    projectId: 'niche-ai-mvp-0215',
    storageBucket: 'niche-ai-mvp-0215.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKv0AotozZ5eRz0fab6mufQ5v-UMumR_M',
    appId: '1:936033037093:ios:6175f68add31b74cd488cc',
    messagingSenderId: '936033037093',
    projectId: 'niche-ai-mvp-0215',
    storageBucket: 'niche-ai-mvp-0215.firebasestorage.app',
    iosBundleId: 'com.mentalcoach.nicheAiCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKv0AotozZ5eRz0fab6mufQ5v-UMumR_M',
    appId: '1:936033037093:ios:6175f68add31b74cd488cc',
    messagingSenderId: '936033037093',
    projectId: 'niche-ai-mvp-0215',
    storageBucket: 'niche-ai-mvp-0215.firebasestorage.app',
    iosBundleId: 'com.mentalcoach.nicheAiCompanion',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqmFGuquOjRmBnuw_6BttjbP2jfHD59Ik',
    appId: '1:936033037093:web:b86099e4cce44f90d488cc',
    messagingSenderId: '936033037093',
    projectId: 'niche-ai-mvp-0215',
    authDomain: 'niche-ai-mvp-0215.firebaseapp.com',
    storageBucket: 'niche-ai-mvp-0215.firebasestorage.app',
  );
}
